stages:
  - build

before_script:
  - apk add --no-cache bash
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN

nginx:1.17:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh nginx:1.17-alpine liteacz/nginx:1.17 . Dockerfile
  only:
    - tags
    - web
  when: manual
