#!/bin/sh

[ -z $WORKER_PROCESSES ] && WORKER_PROCESSES="auto"
[ -z $WORKER_CONNECTIONS ] && WORKER_CONNECTIONS="51200"
[ -z $WORKER_RLIMIT_NO_FILE ] && WORKER_RLIMIT_NO_FILE="51200"

sed -i -e "
s~\$WORKER_PROCESSES~$WORKER_PROCESSES~g
s~\$WORKER_CONNECTIONS~$WORKER_CONNECTIONS~g
s~\$WORKER_RLIMIT_NO_FILE~$WORKER_RLIMIT_NO_FILE~g
" /etc/nginx/nginx.conf
